export const PIZZAS = [
  { id: 1, name: "Supreme Delight" },
  { id: 2, name: "Margherita Bliss" },
  { id: 3, name: "Pepperoni Passion" },
  { id: 4, name: "Veggie Delight" },
  { id: 5, name: "BBQ Chicken Feast" },
  { id: 6, name: "Hawaiian Paradise" },
  { id: 7, name: "Meat Lover's Dream" },
  { id: 8, name: "Mediterranean Marvel" },
  { id: 9, name: "Pesto Perfection" },
  { id: 10, name: "Four Cheese Fiesta" },
  { id: 11, name: "Spicy Sriracha Sensation" },
  { id: 12, name: "Truffle Mushroom Magic" },
  { id: 13, name: "Buffalo Chicken Bonanza" },
  { id: 14, name: "Classic Italiano" },
  { id: 15, name: "Garden Fresh HarvestSupreme Delight" },
  { id: 16, name: "Margherita Bliss" },
  { id: 17, name: "Pepperoni Passion" },
  { id: 18, name: "Veggie Delight" },
  { id: 19, name: "BBQ Chicken Feast" },
  { id: 20, name: "Hawaiian Paradise" },
  { id: 21, name: "Meat Lover's Dream" },
  { id: 22, name: "Mediterranean Marvel" },
  { id: 23, name: "Pesto Perfection" },
  { id: 24, name: "Four Cheese Fiesta" },
  { id: 25, name: "Spicy Sriracha Sensation" },
  { id: 26, name: "Truffle Mushroom Magic" },
  { id: 27, name: "Buffalo Chicken Bonanza" },
  { id: 28, name: "Classic Italiano" },
  { id: 29, name: "Garden Fresh Harvest" },
];
export const DRINKS = [
  { id: 1, name: "Coca-Cola" },
  { id: 2, name: "Pepsi" },
  { id: 3, name: "Sprite" },
  { id: 4, name: "Mountain Dew" },
  { id: 5, name: "Dr Pepper" },
  { id: 6, name: "Fanta" },
];
